In [1]:
import numpy as np

In [2]:
new_array=[1,2,3,4,5,6]

In [3]:
new_array

[1, 2, 3, 4, 5, 6]

In [16]:
np.array(new_array)

array([1, 2, 3, 4, 5, 6])

In [5]:
arr

array([1, 2, 3, 4, 5, 6])

In [6]:
llis=[[2,3,4],[2,3,45],[234,234,2345]]

In [7]:
llis

[[2, 3, 4], [2, 3, 45], [234, 234, 2345]]

In [15]:
np.array(llis)

array([[   2,    3,    4],
       [   2,    3,   45],
       [ 234,  234, 2345]])

In [9]:
ar

array([[   2,    3,    4],
       [   2,    3,   45],
       [ 234,  234, 2345]])

In [10]:
np.arrange(0,10,2)

AttributeError: module 'numpy' has no attribute 'arrange'

In [14]:
np.arange(0,10,2)



array([0, 2, 4, 6, 8])

In [13]:
p

array([0, 2, 4, 6, 8])

In [21]:
np.zeros((5,5))




array([[ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.]])

In [22]:
np.ones(2)

array([ 1.,  1.])

AttributeError: module 'numpy' has no attribute 'twice'

In [28]:
np.linspace(0,90,40)

array([  0.        ,   2.30769231,   4.61538462,   6.92307692,
         9.23076923,  11.53846154,  13.84615385,  16.15384615,
        18.46153846,  20.76923077,  23.07692308,  25.38461538,
        27.69230769,  30.        ,  32.30769231,  34.61538462,
        36.92307692,  39.23076923,  41.53846154,  43.84615385,
        46.15384615,  48.46153846,  50.76923077,  53.07692308,
        55.38461538,  57.69230769,  60.        ,  62.30769231,
        64.61538462,  66.92307692,  69.23076923,  71.53846154,
        73.84615385,  76.15384615,  78.46153846,  80.76923077,
        83.07692308,  85.38461538,  87.69230769,  90.        ])

In [30]:
np.eye(8)

array([[ 1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  1.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  1.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  1.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  1.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.]])

In [31]:
np.random.rand(6)

array([ 0.84939137,  0.94989241,  0.7866338 ,  0.39080046,  0.45703887,
        0.76941196])

In [32]:
np.random.rand(6,6)


array([[ 0.92922678,  0.57288761,  0.94201329,  0.09491237,  0.48161585,
         0.16759656],
       [ 0.88939598,  0.09743872,  0.41238658,  0.96007241,  0.50186845,
         0.50859066],
       [ 0.25984799,  0.87510674,  0.59447649,  0.2045851 ,  0.75993943,
         0.58997239],
       [ 0.18001061,  0.83223348,  0.08168534,  0.67763686,  0.2878596 ,
         0.81432832],
       [ 0.90505478,  0.62099076,  0.95260342,  0.73867185,  0.14143853,
         0.67388655],
       [ 0.63193579,  0.46555162,  0.3776902 ,  0.16537899,  0.47756871,
         0.83669142]])

In [33]:
np.random.randint(1,10,9)


array([4, 9, 2, 4, 8, 9, 3, 6, 8])

In [39]:
arr=np.random.rand(5,5)

In [40]:
arr

array([[ 0.08541691,  0.59931947,  0.38585768,  0.48745129,  0.26339692],
       [ 0.57737049,  0.77026139,  0.85076623,  0.43910054,  0.5160511 ],
       [ 0.48336646,  0.56349934,  0.03929129,  0.41766167,  0.12620508],
       [ 0.2527614 ,  0.88764296,  0.9121931 ,  0.00503694,  0.00459742],
       [ 0.38023209,  0.12832673,  0.85054042,  0.8817467 ,  0.84220971]])

In [41]:
arr.reshape(5,5)

array([[ 0.08541691,  0.59931947,  0.38585768,  0.48745129,  0.26339692],
       [ 0.57737049,  0.77026139,  0.85076623,  0.43910054,  0.5160511 ],
       [ 0.48336646,  0.56349934,  0.03929129,  0.41766167,  0.12620508],
       [ 0.2527614 ,  0.88764296,  0.9121931 ,  0.00503694,  0.00459742],
       [ 0.38023209,  0.12832673,  0.85054042,  0.8817467 ,  0.84220971]])

In [46]:
ar=np.arange(90)

In [47]:
ar

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89])

In [51]:
ar.reshape(9,10)


array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89]])

In [56]:
np.random.randint(34)

32

In [57]:
ar.max()

89

In [59]:
ar.argmax()

89

In [61]:
ar.argmin()

0

In [63]:
from numpy.random import randint

In [64]:
randint(89)

51

In [1]:
import numpy as np

In [3]:
ar=np.arange(0,12)

In [4]:
ar

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [5]:
ar[0:]


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [6]:
ar[0:8]

array([0, 1, 2, 3, 4, 5, 6, 7])

In [7]:
ar[::-1]

array([11, 10,  9,  8,  7,  6,  5,  4,  3,  2,  1,  0])

In [10]:
slice_array=np.arange(0,10)

slice_array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
slice_array[:]=9

In [12]:
slice_array

array([9, 9, 9, 9, 9, 9, 9, 9, 9, 9])

In [13]:
arr=slice_array[:]

In [14]:
arr

array([9, 9, 9, 9, 9, 9, 9, 9, 9, 9])

In [42]:

arr_2d =[[2,3,4],[5,6,7],[3,4,7]]


In [43]:
np.array(arr_2d)


array([[2, 3, 4],
       [5, 6, 7],
       [3, 4, 7]])

In [51]:
arr_2d(2,3)



TypeError: 'list' object is not callable

In [52]:
arr=np.arange(0,17)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16])

In [53]:
arr>9

array([False, False, False, False, False, False, False, False, False, False], dtype=bool)

In [55]:
arr[arr<9]



array([], dtype=int32)

In [60]:
arr_2d=np.arange(50).reshape(5,10)


In [61]:
arr_2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [63]:
arr_2d[:2,3:]



array([[ 3,  4,  5,  6,  7,  8,  9],
       [13, 14, 15, 16, 17, 18, 19]])

In [69]:
arr_2d[3:4,2:4]






array([[32, 33]])